In [3]:
import torch

### 연습문제


#### 문제 1

2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요.

In [4]:
a = torch.rand(3,3)
a = a.unsqueeze(0)
print(a)
print(a.shape)

tensor([[[0.9815, 0.2410, 0.9313],
         [0.8618, 0.7566, 0.7840],
         [0.0465, 0.1310, 0.9364]]])
torch.Size([1, 3, 3])


#### 문제 2 

이전 텐서에 추가한 차원을 삭제하세요.

In [5]:
a = a.squeeze(0)
print(a.shape)

torch.Size([3, 3])


#### 문제 3

[3, 7) 범위를 갖는 5x3 크기의 랜덤한 텐서를 만드세요.

In [6]:
3 + torch.rand(5, 3) * 4

tensor([[4.3022, 6.3183, 6.2619],
        [5.4592, 3.7180, 4.8678],
        [4.0875, 6.8846, 4.7043],
        [6.1421, 4.7265, 4.9882],
        [4.9893, 5.9891, 3.1111]])

#### 문제 4

정규 분포(평균=0, 표준편차=1)를 사용해 텐서를 만드세요.

In [7]:
a = torch.rand(3,3)
a.normal_(mean=0, std=1)

tensor([[-0.1233, -1.2965,  0.3288],
        [ 1.9206,  1.0155, -0.1445],
        [ 1.8106, -1.2401,  1.1195]])

#### 문제 5

텐서 `torch.Tensor([1, 1, 1, 0, 1])`에서 0이 아닌 원소의 인덱스를 추출하세요.

In [12]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

#### 문제 6

(3,1) 크기가 인 랜덤한 텐서를 만들고 네 벌을 복사해 쌓으세요.

In [13]:
a = torch.rand(3,1)
a.expand(3,4)

tensor([[0.3029, 0.3029, 0.3029, 0.3029],
        [0.9929, 0.9929, 0.9929, 0.9929],
        [0.0456, 0.0456, 0.0456, 0.0456]])

#### 문제 7

두 개의 2차원 행렬(`a=torch.rand(3,4,5)`, `b=torch.rand(3,5,4)`)의 배치 행렬 곱셈(batch matrix-matrix product)을 계산하세요.

In [14]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
torch.bmm(a, b)

tensor([[[1.3284, 0.9954, 1.4598, 1.3857],
         [0.4954, 1.1153, 0.6763, 1.6418],
         [1.1208, 0.8512, 0.9887, 1.4874],
         [1.1533, 1.2554, 1.2809, 1.8967]],

        [[1.2472, 0.9899, 1.5995, 1.1768],
         [1.4145, 0.7561, 1.5410, 1.3459],
         [1.3702, 1.1845, 2.2352, 1.1510],
         [1.4689, 1.0288, 2.0256, 1.1828]],

        [[0.8299, 0.5774, 0.4123, 1.1998],
         [1.1851, 0.7824, 0.8384, 1.0561],
         [0.5806, 0.4624, 0.6944, 0.7372],
         [0.9389, 0.6924, 1.1813, 1.0082]]])

#### 문제 8

3차원 행렬(`a=torch.rand(3,4,5)`)과 2차원 행렬(`b=torch.rand(5,4)`)의 배치 행렬 곱셈을 계산하세요.

In [15]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.1506, 1.8988, 1.6642, 1.2088],
         [1.4888, 1.9166, 1.6845, 1.3777],
         [1.5287, 1.8621, 1.4410, 1.0866],
         [1.7266, 2.2409, 1.8065, 1.3117]],

        [[1.0590, 1.1663, 0.9001, 0.7779],
         [0.7712, 1.3441, 1.1405, 0.7344],
         [1.3131, 2.2432, 1.6170, 0.9948],
         [1.3534, 1.8553, 1.6843, 1.3382]],

        [[1.2576, 1.9003, 1.6082, 1.1608],
         [1.2639, 2.2156, 1.6445, 1.0445],
         [0.8484, 1.8897, 1.4308, 0.8659],
         [0.5639, 0.8376, 0.6702, 0.5688]]])