### 연습문제


#### 문제 1

2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요.

In [ ]:
a = torch.rand(3,3)
a = a.unsqueeze(0)
print(a)
print(a.shape)

tensor([[[0.5311, 0.6449, 0.7224],
         [0.4416, 0.3634, 0.8818],
         [0.9874, 0.7316, 0.2814]]])
torch.Size([1, 3, 3])


#### 문제 2 

이전 텐서에 추가한 차원을 삭제하세요.

In [ ]:
a = a.squeeze(0)
print(a.shape)

torch.Size([3, 3])


#### 문제 3

[3, 7) 범위를 갖는 5x3 크기의 랜덤한 텐서를 만드세요.

In [ ]:
3 + torch.rand(5, 3) * 4

tensor([[3.2603, 3.0260, 5.0138],
        [4.2326, 4.4967, 4.7188],
        [6.8914, 6.8958, 4.8130],
        [4.3994, 5.9713, 4.8404],
        [3.0970, 5.6519, 6.9147]])

#### 문제 4

정규 분포(평균=0, 표준편차=1)를 사용해 텐서를 만드세요.

In [ ]:
a = torch.rand(3,3)
a.normal_(mean=0, std=1)

tensor([[ 0.5548, -0.0845,  0.5903],
        [-1.0032, -1.7873,  0.0538],
        [ 0.8246, -0.5723, -0.4876]])

#### 문제 5

텐서 `torch.Tensor([1, 1, 1, 0, 1])`에서 0이 아닌 원소의 인덱스를 추출하세요.

In [ ]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

#### 문제 6

(3,1) 크기가 인 랜덤한 텐서를 만들고 네 벌을 복사해 쌓으세요.

In [ ]:
a = torch.rand(3,1)
a.expand(3,4)

tensor([[0.6889, 0.6889, 0.6889, 0.6889],
        [0.8389, 0.8389, 0.8389, 0.8389],
        [0.1780, 0.1780, 0.1780, 0.1780]])

#### 문제 7

두 개의 2차원 행렬(`a=torch.rand(3,4,5)`, `b=torch.rand(3,5,4)`)의 배치 행렬 곱셈(batch matrix-matrix product)을 계산하세요.

In [ ]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
torch.bmm(a, b)

tensor([[[1.8631, 0.5816, 1.6206, 2.1847],
         [1.4829, 0.6082, 1.3175, 1.5142],
         [1.0181, 0.2124, 0.7511, 1.2270],
         [1.8149, 0.4185, 1.7273, 1.9657]],

        [[0.2883, 1.4538, 0.9522, 1.3637],
         [0.6061, 0.8883, 0.5272, 1.2686],
         [0.6755, 1.3005, 0.6378, 1.5955],
         [0.3848, 1.5427, 1.0912, 1.3246]],

        [[2.0046, 2.0660, 1.6496, 1.3565],
         [2.0920, 2.0059, 1.7782, 1.5390],
         [1.8414, 2.0416, 1.3245, 1.0922],
         [1.1424, 1.4117, 0.9156, 0.6832]]])

#### 문제 8

3차원 행렬(`a=torch.rand(3,4,5)`)과 2차원 행렬(`b=torch.rand(5,4)`)의 배치 행렬 곱셈을 계산하세요.

In [ ]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.7605, 2.0294, 1.5650, 0.6206],
         [1.3520, 1.8327, 1.4261, 0.8760],
         [1.5696, 2.2761, 1.9558, 0.7985],
         [1.2448, 1.3463, 1.1928, 0.5456]],

        [[1.7564, 1.8829, 1.5684, 0.7319],
         [1.7715, 2.0721, 1.6825, 0.7578],
         [1.4518, 2.1728, 1.8737, 0.8913],
         [1.3978, 1.6048, 1.3362, 0.5736]],

        [[1.7872, 2.4103, 1.9224, 0.8451],
         [1.9918, 2.5528, 1.8675, 1.0383],
         [1.7120, 2.0994, 1.5413, 0.9485],
         [1.4417, 1.9108, 1.5602, 0.7331]]])